name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: '0'
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - uses: c-hive/gha-yarn-cache@v2
    - name: 🚀 Deploy 🚀
      run: make deploy